[[library]]
name = "libsundials_arkode"

[[library]]
name = "libsundials_cvode"

[[library]]
name = "libsundials_cvodes"

[[library]]
name = "libsundials_ida"

[[library]]
name = "libsundials_idas"

[[library]]
name = "libsundials_kinsol"

[[library]]
name = "libsundials_nvecmanyvector"

[[library]]
name = "libsundials_nvecserial"

[[library]]
name = "libsundials_sunlinsolband"

[[library]]
name = "libsundials_sunlinsoldense"

[[library]]
name = "libsundials_sunlinsolklu"

[[library]]
name = "libsundials_sunlinsollapackband"

[[library]]
name = "libsundials_sunlinsollapackdense"

[[library]]
name = "libsundials_sunlinsolpcg"

[[library]]
name = "libsundials_sunlinsolspbcgs"

[[library]]
name = "libsundials_sunlinsolspfgmr"

[[library]]
name = "libsundials_sunlinsolspgmr"

[[library]]
name = "libsundials_sunlinsolsptfqmr"

[[library]]
name = "libsundials_sunmatrixband"

[[library]]
name = "libsundials_sunmatrixdense"

[[library]]
name = "libsundials_sunmatrixsparse"

[[library]]
name = "libsundials_sunnonlinsolfixedpoint"

[[library]]
name = "libsundials_sunnonlinsolnewton"

[[library]]
name = "libsundials_core"
