.\" Manpage for sworkstyle.
.\" Contact lyr-7d1h@pm.me to correct errors or typos.
.TH man 1 "26 March 2021" "1.0" "sworkstyle man page"
.SH NAME
sworkstyle - The Swayest Workstyle 
.SH DESCRIPTION
Swayest Workstyle. 

This tool will rename workspaces to the icons configured.
Config can be found in $HOME/.config/sworkstyle"
.SH SYNOPSIS
sworkstyle [FLAGS]
.SH FLAGS
-h, --help
      Display a description of this program.

--log-level
      Either "error", "warn", "info", "debug". Uses "warn" by default"
.SH EXIT STATUS
0      Successful program execution.

1      Unsuccessful program execution.

101    The program panicked.
.SH AUTHOR
Lyr-7d1h <lyr-7d1h@pm.me>