[[library]]
name = "libwebp"

[[library]]
name = "libwebpdecoder"

[[library]]
name = "libwebpdemux"

[[library]]
name = "libwebpmux"

[[binary]]
name = "cwebp"

[[binary]]
name = "dwebp"

[[binary]]
name = "gif2webp"

[[binary]]
name = "img2webp"

[[binary]]
name = "webpinfo"

[[binary]]
name = "webpmux"
