post_install() {
	echo ""
        echo "An example systems configuration file will be created at ~/.emulationstation/es_systems.cfg on first run."
        echo "See https://github.com/RetroPie/EmulationStation/blob/master/SYSTEMS.md on how to tell EmulationStation"
        echo "what systems you have, what platform they correspond to (for scraping), and where the games are located."
        echo ""
        echo "See https://github.com/RetroPie/EmulationStation#writing-an-es_systemscfg for a configuration file example."
        echo ""
        echo "Default theme is quite ugly, you can clone one like https://github.com/RetroPie/es-theme-carbon"
        echo "in ~/.emulationstation/themes/{theme name} and select it in the settings."
        echo "See https://github.com/RetroPie/EmulationStation/blob/master/THEMES.md for documentation."
	echo ""
}
