maintainers:
- github: isjerryxiao
  email: archcn@mail.jerryxiao.cc
build_prefix: extra-x86_64

pre_build_script: aur_pre_build(maintainers=['t-8ch', 'blakkheim'])

post_build: aur_post_build

update_on:
- source: aur
  aur: needrestart
- alias: perl
