.TH MAKEMKV "1" "May 2014" "MakeMKV 1.8"

\" Completely disable hyphenation. It is a very annoying feature while reading man pages, in my opinion.
.nh

.SH NAME
MakeMKV \- Decrypt DVD and Blu-ray discs to your hard disk using a simple GUI.

.SH SYNOPSIS
.B makemkv

.SH DESCRIPTION
MakeMKV is a simple solution to convert video that you own into a free and patents-unencumbered format which can be played everywhere. MakeMKV is a format converter, otherwise called a "transcoder". It converts the video clips from proprietary (and usually encrypted) disc into a set of MKV files, preserving most information but not changing it in any way. Additionally MakeMKV can instantly stream decrypted video without intermediate conversion to wide range of media players.

.SH AUTHOR
This manual page was written by Karl Lenz <xorangekiller@gmail.com> for the Debian project (but may be used by others).

.SH COPYRIGHT
2007-2014 GuinpinSoft Inc.

Copying and distribution of this file, with or without modification, are permitted in any medium without royalty provided the copyright notice and this notice are preserved.

MakeMKV is provided "as is" with no warranty. This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 2.1 of the License, or (at your option) any later version. On Debian systems, the complete text of the GNU Lesser General Public License version 2.1 can be found in "/usr/share/common-licenses/LGPL-2.1".

.SH SEE\ ALSO
.BR makemkvcon (1),
.BR mmdtsdec (1),
.BR ffmpeg (1),
.BR vlc (1),
.BR mpv (1)
