post_install() {
  useradd -r -U -d /var/lib/lantern -s /bin/false lantern &>/dev/null
  chown -R lantern:lantern var/lib/lantern
  echo <<EOF
lantern-bin port settings are randomized. find your settings from
            /var/lib/lantern/.lantern/settings.yaml.
lantern-bin massive logs to journal has been disabled.
EOF
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  userdel -rf lantern
}
