#!/bin/bash
# Copyright Sebastian Wiesner <sebastian@swsnr.de>
# Copyright Franklyn Tackitt <franklyn@tackitt.net>
# Copyright Kevin Del Castillo <quebin31@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -euo pipefail
# Inherit set -e down to command substitutions
shopt -s inherit_errexit

extract_kernel_version() {
    local heads
    heads="${1%/pkgbase}"
    echo "${heads##*/}"
}

install_uefi_images() {
    local kernel_versions
    local rebuild_all
    local line
    local version
    local dracut_args

    kernel_versions=()
    rebuild_all=0
    dracut_args=(-q -f --uefi)

    while read -r line; do
        case "${line}" in
        usr/lib/modules/*/pkgbase)
            kernel_versions+=("$(extract_kernel_version "${line}")")
            ;;
        *)
            rebuild_all=1
            break
            ;;
        esac
    done

    if ((rebuild_all)); then
        echo ":: Rebuilding all unified kernel images"
        dracut "${dracut_args[@]}" --regenerate-all --force
    else
        for version in "${kernel_versions[@]}"; do
            echo ":: Building unified kernel image for ${version}"
            dracut "${dracut_args[@]}" --kver "${version}"
        done
    fi
}

remove_uefi_images() {
    local efi
    local machine_id
    local os_release
    local line
    local version
    local image

    efi="$(bootctl -p)"
    machine_id="$(</etc/machine-id)"

    # We source os-release for the BUILD_ID variable we need for the full image
    # path.
    #
    # See os-release(5) about this code for reading os-release.
    test -e /etc/os-release && os_release='/etc/os-release' || os_release='/usr/lib/os-release'
    # shellcheck source=/etc/os-release
    . "${os_release}"

    while read -r line; do
        case "${line}" in
        usr/lib/modules/*/pkgbase)
            version="$(extract_kernel_version "${line}")"
            image="${efi}/EFI/Linux/linux-${version}-${machine_id}-${BUILD_ID}.efi"
            echo ":: Removing unified kernel image for ${version} from ${image}"
            rm -f "${image}"
            ;;
        *) ;;

        esac
    done
}

case "$1" in
"install")
    install_uefi_images
    ;;
"remove")
    remove_uefi_images
    ;;
*)
    echo "Unsupported argument: $1" 1>&2
    exit 1
    ;;
esac
