pref("app.update.enabled", false);
pref("browser.download.useDownloadDir",false);
pref("browser.feeds.showFirstRunUI", false);
pref("browser.startup.homepage_override.mstone", "ignore");
pref("browser.rights.3.shown", true);
pref("browser.tabs.warnOnClose", false);
pref("browser.tabs.loadInBackground",false);
pref("browser.tabs.closeWindowWithLastTab", false);
pref("browser.urlbar.suggest.searches", true);
pref("browser.urlbar.trimURLs", false);
pref("devtools.webide.enabled", false);
pref("extensions.autoDisableScopes", 0);
pref("full-screen-api.approval-required", false);
pref("layout.word_select.eat_space_to_next_word", false); 
pref("lightweightThemes.recommendedThemes", "");
pref("loop.enabled", false);
pref("extensions.pocket.enabled", false);
pref("media.peerconnection.enabled", false);
pref("startup.homepage_welcome_url", "");
pref("security.OCSP.enabled", 0);
pref("security.mixed_content.block_active_content", false);
pref("security.mixed_content.block_display_content", false);
pref("services.sync.engine.addons",false);
pref("services.sync.engine.bookmarks",true);
pref("services.sync.engine.history",false);
pref("services.sync.engine.passwords",false);
pref("services.sync.engine.prefs",false);
pref("services.sync.engine.tabs",false);
pref("network.allow-experiments", false);
pref("breakpad.reportURL", "");
pref("browser.selfsupport.url", "");
pref("toolkit.telemetry.unified", false);
pref("toolkit.telemetry.enabled", false);
pref("toolkit.telemetry.unifiedIsOptIn", true);
pref("toolkit.telemetry.server", "");
pref("toolkit.telemetry.archive.enabled", false);
pref("toolkit.telemetry.cachedClientID", "");
pref("datareporting.healthreport.uploadEnabled", false);
pref("datareporting.healthreport.documentServerURI", "");
pref("datareporting.healthreport.service.enabled", false);
pref("datareporting.healthreport.about.reportUrl", "");
pref("datareporting.healthreport.about.reportUrlUnified", "");
pref("datareporting.policy.dataSubmissionEnabled", false);
pref("datareporting.policy.dataSubmissionEnabled.v2", false);
pref("browser.safebrowsing.enabled", false);
pref("browser.safebrowsing.malware.enabled", false);
