#!/bin/sh

# inspired by https://aur.archlinux.org/cgit/aur.git/tree/hmcl-launch-script?h=hmcl

WORKDIR=${XDG_CONFIG_HOME:-$HOME/.config}/waylyrics
mkdir -p "$WORKDIR"
cd "$WORKDIR"

mkdir -p themes

[ -f "config.toml" ] || install -Dm644 /usr/share/waylyrics/config.toml .
[ -f "themes/default.css" ] || install -Dm644 /usr/share/waylyrics/themes/default.css themes/

exec /usr/bin/waylyrics
