post_install() {
    cat <<EOF
=> to use this package, add

(add-to-list 'load-path' "/usr/share/emacs/site-lisp/markdown-preview-mode/")    
(require 'markdown-preview-mode)

to the init file

=> to render Mathjax, add

(add-to-list 'markdown-preview-javascript "http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML")

to the init file
EOF
}

post_upgrade() {
    post_install $1
}
