post_install() {
    echo ">>> Enable the plugin:"
    echo "Settings -> Configure Krita -> Python Plugin Manager -> Blender Layer"
    echo ">>>"
    echo ">>> (If the Blender Layer option is not visible under"
    echo ">>> Settings -> Dockers, you may need to restart Krita.)"
    echo ">>>"
    echo ">>> To show the plugin docker:"
    echo "Settings -> Dockers -> Blender Layer"
}

post_upgrade() {
    post_install
}
