version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.sh",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "0001-build-do-not-hardcode-compile-and-link-flags.patch",
    "0002-build-respect-WITH_SYSTEM_PROVIDED_3PARTY-for-3party.patch",
]
SPDX-FileCopyrightText = "Organic Maps contributors"
SPDX-License-Identifier = "Apache-2.0"
