[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.sh",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "0001-root-cmake-system-3party.patch",
    "0002-drape-tests-private.patch",
    "0003-fix-linker-flags.patch",
]
SPDX-FileCopyrightText = "Organic Maps contributors"
SPDX-License-Identifier = "MIT"
