[[binary]]
name = "scp"

[[binary]]
name = "sftp"

[[binary]]
name = "ssh"

[[binary]]
name = "ssh_add"
file = "ssh-add"

[[binary]]
name = "ssh_agent"
file = "ssh-agent"

[[binary]]
name = "ssh_keygen"
file = "ssh-keygen"

[[binary]]
name = "ssh_keyscan"
file = "ssh-keyscan"
