maintainers:
- github: lilydjwg
update_on:
- source: github
  github: meganz/MEGAcmd
  use_max_tag: true
  include_regex: ".*_Linux"
- alias: icu
pre_build_script: |
  update_pkgver_and_pkgrel(_G.newver.removesuffix('_Linux'))
post_build: git_pkgbuild_commit
