#!/bin/sh

# this is from /etc/init.d/vmware-USBArbitrator
# changed to work on uids >= 1000
for user in `awk -F'[/:]' '{if ($3 == 0 || ($3 >= 1000 && $3 != 65534)) print $1}' /etc/passwd`
   do
      aUser=$user
      aGroup=`id -g $aUser`
      aUID=`id -u $aUser`
      if ! [ -f /var/run/vmware/"$aUID" ] ; then
         mkdir -p /var/run/vmware/"$aUID"
         chown -R -- "$aUser":"$aGroup" /var/run/vmware/"$aUID"
         chmod 700 /var/run/vmware/"$aUID"
      fi
   done

/usr/lib/vmware/view/usb/vmware-usbarbitrator
