# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Grey Christoforo <grey@christoforo.net>

_gemname=crass
pkgname=ruby-$_gemname
pkgver=1.0.2
pkgrel=1
pkgdesc='CSS parser based on the CSS Syntax Level 3 spec.'
arch=(any)
url='https://github.com/rgrove/crass/'
license=(MIT)
depends=(ruby)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('5a855504ff288cd8c36482c26d965d05b370dbbd')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
