# Maintainer: Bin Jin <bjin@protonmail.com>

pkgname=oh-my-pi
pkgver=18.8.8
pkgrel=1
pkgdesc="Coding agent with the IDE wired in"
arch=('x86_64')
url="https://omp.sh/"
license=('MIT')
depends=('gcc-libs' 'glibc' 'icu' 'oniguruma' 'opus' 'pcre2' 'zstd')
makedepends=('bun' 'cargo' 'cmake')
# Keep the optional grammar package in sync with the generated registry.
# Without it, upstream still downloads missing grammars on demand.
_grammar_release=1
optdepends=(
    'alsa-lib: ALSA fallback for live voice, STT, and TTS'
    'at-spi2-core: Linux accessibility backend for the computer tool'
    'chromium: system browser for the browser tool'
    'git: repository integration and isolated task worktrees'
    'julia: Julia eval backend'
    'libpulse: PulseAudio/PipeWire-Pulse client backend for live voice, STT, and TTS'
    "oh-my-pi-grammars-bin=${_grammar_release}: preinstalled WebAssembly grammars for AST tools"
    'python: Python 3.10+ eval backend'
    'xdg-desktop-portal: Wayland ScreenCast and RemoteDesktop portals for the computer tool'
    'xdg-desktop-portal-impl: compositor-specific backend for Wayland computer tool portals'
)
options=('!lto' '!strip')
# Version of the `opus` crate pinned by the workspace lockfile; the checksum
# below is the one Cargo.lock records for it. See prepare() for why a copy of
# the crate is needed.
_opus_ver=0.4.0
# Upstream builds with a pinned nightly; this package builds on stable (plus
# RUSTC_BOOTSTRAP=1 for the crate-level feature gates), so it needs a stable
# release that ships every library API upstream calls. 1.98 stabilized
# Option/Result::map_or_default, first used in 18.7.0.
_rust_min=1.98.0
source=(
    "${pkgname}-${pkgver}.tar.gz::https://github.com/can1357/oh-my-pi/archive/v${pkgver}.tar.gz"
    "https://static.crates.io/crates/opus/opus-${_opus_ver}.crate"
    "skip-native-embed-for-aur.patch"
    "system-grammars-for-aur.patch"
)
sha256sums=('3bd2ca754632c99eff90ce80471ed3aa58cba70f2b070b55ca47e84ee632224c'
            '33718946cc77d4032911d4efe03a66dbcbfbd2bb16c3da06aaeadcc637c32216'
            'd60c5282c2eebcde70c70b67d49b3fb8105c15d232d29851c68d858a9195acb6'
            '724888738f0e886693d8a6aa6cfd5f6dba9a98122353e4636a9ca946ae1fa9e7')

_variants=('baseline:x86-64-v2' 'modern:x86-64-v3')
_cargo_features=()
_enable_wayland_screencast=1

if (( _enable_wayland_screencast )); then
    depends+=('libpipewire')
    makedepends+=('clang')
    _cargo_features=(--features wayland-pipewire)
fi

prepare() {
    cd "${srcdir}/${pkgname}-${pkgver}"

    # An older stable dies deep in the cargo build with E0658 "use of unstable
    # library feature", which reads like a packaging bug; fail up front.
    local _rustc _rustc_ver
    _rustc=$(RUSTUP_TOOLCHAIN=stable rustc --version)
    _rustc_ver=${_rustc#rustc }
    _rustc_ver=${_rustc_ver%% *}
    if (( $(vercmp "${_rustc_ver}" "${_rust_min}") < 0 )); then
        error "rustc ${_rust_min} or newer is required, found: ${_rustc}"
        plain "Upgrade the rust package, or run 'rustup update stable' with rustup."
        return 1
    fi

    patch -p1 -i "${srcdir}/skip-native-embed-for-aur.patch"
    patch -p1 -i "${srcdir}/system-grammars-for-aur.patch"

    local _grammar_prefix="//! Generated by \`bun run gen:grammars\` from stencil-hq/wasm-grammars v${_grammar_release}; do"
    local _grammar_header
    if ! IFS= read -r -N "${#_grammar_prefix}" _grammar_header \
        < crates/pi-ast/src/language/wasm_grammars.rs \
        || [[ $_grammar_header != "$_grammar_prefix" ]]; then
        warning "Grammar registry does not start with the expected v${_grammar_release} header; check oh-my-pi-grammars-bin compatibility. Continuing build."
    fi

    RUSTUP_TOOLCHAIN=stable cargo fetch --locked --target x86_64-unknown-linux-gnu

    # `opus` pulls in opusic-sys with default features, and the default feature
    # `bundled` cmake-builds the crate's vendored libopus copy and links it
    # statically. Cargo features are additive, so the workspace cannot switch
    # that default off; the only lever is the wrapper's own manifest. Patch a
    # copy of it and redirect the graph there: with `bundled` off, opusic-sys'
    # build script just emits `cargo:rustc-link-lib=dylib=opus` and links the
    # system library (opusic-sys 0.7.5 build.rs, non-bundled `run()` branch).
    sed -i '/^\[dependencies\.opusic-sys\]$/a default-features = false' \
        "${srcdir}/opus-${_opus_ver}/Cargo.toml"
    cat >"${srcdir}/system-opus.toml" <<EOF
[patch.crates-io]
opus = { path = "${srcdir}/opus-${_opus_ver}" }
EOF
    # Re-resolve with the patch in place. The lockfile delta is pure deletion
    # (the `cmake` crate and opusic-sys' build-dependency edge to it), so this
    # needs no downloads and build() stays --frozen.
    RUSTUP_TOOLCHAIN=stable cargo fetch --offline --target x86_64-unknown-linux-gnu \
        --config "${srcdir}/system-opus.toml"

    # Vendored array.h type-punning can cause GCC strict-aliasing miscompiles.
    # Haskell is now WASM, but native Bash/HTML/Python/YAML retain pre-fix headers
    # (fixed in tree-sitter 0.26.4, tree-sitter/tree-sitter@ed6e42c).
    # cc-rs exposes CARGO_PKG_NAME to scope the workaround to tree-sitter crates.
    local _cc
    _cc=$(command -v "${CC:-cc}")
    cat >"${srcdir}/cc-tree-sitter" <<EOF
#!/bin/sh
case \${CARGO_PKG_NAME-} in
*tree-sitter*) set -- "\$@" -fno-strict-aliasing ;;
esac
exec ${_cc} "\$@"
EOF
    chmod +x "${srcdir}/cc-tree-sitter"
}

_build_native() {
    local _variant="$1" _target_cpu="$2"
    local _target_dir="target/${_variant}"

    # The patched opus copy lives outside the workspace, so rustc records its
    # absolute `$srcdir` path in panic locations; strip that prefix. Cargo
    # splits RUSTFLAGS on whitespace, so pass the flags 0x1f-separated.
    #
    # With --remap-path-prefix present, Cargo leaves RUSTFLAGS out of the unit
    # hash that names artifacts and fingerprint dirs, so in a shared target dir
    # both variants map onto the same units and each build recompiles the
    # whole graph over the other's. A target dir per variant keeps both caches
    # warm across makepkg runs.
    RUSTC_BOOTSTRAP=1 \
    CARGO_TARGET_DIR="${_target_dir}" \
    CARGO_ENCODED_RUSTFLAGS="-Ctarget-cpu=${_target_cpu}"$'\x1f'"--remap-path-prefix=${srcdir}/=" \
    CC="${srcdir}/cc-tree-sitter" \
    PCRE2_SYS_STATIC=0 \
    ZSTD_SYS_USE_PKG_CONFIG=1 \
    RUSTONIG_SYSTEM_LIBONIG=1 \
        cargo build --frozen --config "${srcdir}/system-opus.toml" \
            --profile ci --package pi-natives "${_cargo_features[@]}"

    # Fail loudly rather than silently shipping a statically linked libopus if
    # the [patch.crates-io] redirect above ever stops applying.
    readelf -d "${_target_dir}/ci/libpi_natives.so" | grep -Fq libopus.so

    install -Dm755 "${_target_dir}/ci/libpi_natives.so" \
        "packages/natives/native/pi_natives.linux-x64-${_variant}.node"
    # The crate links an empty release-stamp slot; upstream's build-bindings.ts
    # fills it post-link, and the loader rejects an addon without it. Stamp the
    # copy so the cargo artifact (and its fingerprint) stays untouched.
    bun scripts/stamp-native-version.ts \
        "packages/natives/native/pi_natives.linux-x64-${_variant}.node"
}

_build_id() {
    readelf -n "$1" | sed -n 's/.*Build ID: //p'
}

build() {
    cd "${srcdir}/${pkgname}-${pkgver}"

    export RUSTUP_TOOLCHAIN=stable

    bun install --frozen-lockfile
    local _variant
    for _variant in "${_variants[@]}"; do
        _build_native "${_variant%%:*}" "${_variant##*:}"
    done

    unset CROSS_TARGET
    bun --cwd=packages/coding-agent run build
    # JSC bytecode only loads in the Bun build that emitted it; make sure the
    # embedded runtime is the system bun, not a downloaded or foreign one.
    local _want
    _want=$(_build_id /usr/bin/bun)
    if [[ -z $_want || $(_build_id packages/coding-agent/dist/omp) != "$_want" ]]; then
        error "compiled omp does not embed /usr/bin/bun"
        return 1
    fi
}

_install_completions() {
    local _omp_bin="$1"
    local _completion_dir="${srcdir}/completions"
    local _runtime_dir="${srcdir}/completion-runtime"

    rm -rf "${_completion_dir}" "${_runtime_dir}"
    mkdir -p "${_completion_dir}" "${_runtime_dir}/home" "${_runtime_dir}/xdg"

    env HOME="${_runtime_dir}/home" XDG_DATA_HOME="${_runtime_dir}/xdg" \
        "${_omp_bin}" completions bash >"${_completion_dir}/omp.bash"
    env HOME="${_runtime_dir}/home" XDG_DATA_HOME="${_runtime_dir}/xdg" \
        "${_omp_bin}" completions zsh >"${_completion_dir}/_omp"
    env HOME="${_runtime_dir}/home" XDG_DATA_HOME="${_runtime_dir}/xdg" \
        "${_omp_bin}" completions fish >"${_completion_dir}/omp.fish"

    install -Dm644 "${_completion_dir}/omp.bash" "${pkgdir}/usr/share/bash-completion/completions/omp"
    install -Dm644 "${_completion_dir}/_omp" "${pkgdir}/usr/share/zsh/site-functions/_omp"
    install -Dm644 "${_completion_dir}/omp.fish" "${pkgdir}/usr/share/fish/vendor_completions.d/omp.fish"
}

package() {
    cd "${srcdir}/${pkgname}-${pkgver}"

    install -Dm755 "packages/coding-agent/dist/omp" \
        "${pkgdir}/usr/lib/${pkgname}/omp"
    local _variant
    for _variant in "${_variants[@]}"; do
        install -Dm755 "packages/natives/native/pi_natives.linux-x64-${_variant%%:*}.node" \
            "${pkgdir}/usr/lib/${pkgname}/pi_natives.linux-x64-${_variant%%:*}.node"
    done
    install -dm755 "${pkgdir}/usr/bin"
    ln -s "../lib/${pkgname}/omp" "${pkgdir}/usr/bin/omp"
    _install_completions "${pkgdir}/usr/bin/omp"
    install -Dm644 LICENSE "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
}
