#!/bin/bash

# general config

ISATAPD_ROUTER="isatap.tsinghua.edu.cn"
ISATAPD_PID_FILE="/var/run/isatapd.pid"

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
    start)
        stat_busy "Starting isatapd"
        if [ -s $ISATAPD_PID_FILE ]; then
            stat_fail
            stat_busy "isatapd is already running"
            stat_die
        fi
        /usr/bin/isatapd --router $ISATAPD_ROUTER --daemon \
            --pid $ISATAPD_PID_FILE --quiet
        if [ $? -ne 0 ]; then
            stat_fail
        else
            add_daemon isatapd
            stat_done
        fi
        ;;
    stop)
        stat_busy "Stopping isatapd"
        if [ -s $ISATAPD_PID_FILE ]; then
            kill `cat $ISATAPD_PID_FILE` &>/dev/null
            if [ $? -ne 0 ]; then
                stat_fail
            else
                rm_daemon isatapd
                stat_done
            fi
        else
            stat_busy "isatapd is not running"
            stat_fail
        fi
        ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    *)
        echo "usage: $0 {start|stop|restart}"
esac

