post_install() {
    echo ">>> Enable the plugin:"
    echo "Settings -> Configure Krita -> Python Plugin Manager -> AI Image Diffusion"
    echo ">>> To show the plugin docker:"
    echo "Settings -> Dockers -> AI Image Generation"
}

post_upgrade() {
    post_install
}

post_remove() {
    echo ">>> If you want to delete leftover data files, please check:"
    echo "\$HOME/.local/share/krita/ai_diffusion"
}
