post_install() {
  if ! getent group nvidia-persistenced >/dev/null; then
    groupadd -g 143 nvidia-persistenced
  fi
  if ! getent passwd nvidia-persistenced >/dev/null; then
    useradd -c 'NVIDIA Persistence Daemon' -u '143' -g 'nvidia-persistenced' -d '/' -s '/sbin/nologin' nvidia-persistenced
  fi
}

post_remove() {
  if getent group nvidia-persistenced >/dev/null; then
    userdel -f nvidia-persistenced
  fi
}