#!/bin/bash

# Allow users to override command-line options
# Based on Gentoo's chromium package (and by extension, Debian's)
if [[ -f /etc/%pkgname%/default ]]; then
	. /etc/%pkgname%/default
fi

# Prefer user defined CHROMIUM_USER_FLAGS (from env) over system
# default CHROMIUM_FLAGS (from /etc/chromium/default)
OPERA_FLAGS=${OPERA_USER_FLAGS:-$OPERA_FLAGS}

exec /usr/lib/%operabin% $OPERA_FLAGS "$@"
