post_install() {
    echo ""
    echo "To start the client, simply modify /etc/frp/frpc.ini, and start the service by:"
    echo ""
    echo "    systemctl start frpc"
    echo ""
    echo "or create your own config file, for example myconf.ini, and start the service by:"
    echo ""
    echo "    systemctl start frpc@myconf"
    echo ""
    echo "You can also start frps the same way"
    echo ""
}
