post_install () {
	update-desktop-database -q
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
	echo -e "  IceCat user profile directory is set to ~/.gnu/icecat\n  Please, consider to move your profile directory if you want to keep your settings.\n  ==> mv ~/.mozilla/icecat ~/.gnu/"
	update-desktop-database -q
}

post_remove() {
	update-desktop-database -q
}

#op=$1
#shift

#$op $*
