# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Hugo Osvaldo Barrera <hugo@barrera.io>
# Contributor: Anatol Pomozov <anatol.pomozov@gmail.com>

_gemname=mercenary
pkgname=ruby-$_gemname
pkgver=0.3.5
pkgrel=1
pkgdesc='Lightweight and flexible library for writing command-line apps in Ruby.'
arch=(any)
url='https://github.com/jekyll/mercenary'
license=(MIT)
depends=(ruby)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('56884c5ee5a4fea5215dd0bfbd15a376aeaaa4ce')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE.txt" "$pkgdir/usr/share/licenses/$pkgname/LICENSE.txt"
}
