# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Aoibhinn Nic Aoidh <oibindnicaoidh@gmail.com>
# Contributor : Barry Smith <brrtsm@gmail.com>
# Contributor: Florent H. CARRÉ <colundrum@gmail.com>

_gemname=thread_safe
pkgname=ruby-$_gemname
pkgver=0.3.6
pkgrel=1
pkgdesc='Thread-safe collections and utilities for Ruby'
arch=(any)
url='https://github.com/ruby-concurrency/thread_safe'
license=(Apache-2.0)
depends=(ruby)
makedepends=(ruby-rdoc)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('5a60162d065d0f479d61ba0a11734b44f5f7ef19')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
