# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Artem Vorotnikov <artem@vorotnikov.me>

_gemname=rake-compiler
pkgname=ruby-$_gemname
pkgver=0.9.5
pkgrel=1
pkgdesc='Rake-based Ruby Extension (C, Java) task generator.'
arch=(any)
url='https://github.com/rake-compiler/rake-compiler'
license=(MIT)
depends=(ruby)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha512sums=('0891a57a226b0b25b8f3f06c79b6caf3770982280bbbc16fdb2f6ecb0ad9b19ff09721e95ab32c40af4821ed76cde2e80679a59e9e04d6eb3c3ec093802bdb42')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE.txt" "$pkgdir/usr/share/licenses/$pkgname/LICENSE.txt"
}
