version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".gitignore",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*sysusers.conf",
    "*.tmpfiles",
    "*tmpfiles.conf",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
    "lilac.yaml",
    "lilac.py",
    "google-cloud-cli.sh",
    "*.sh",
    "*.conf",
    "*.1",
    "ChangeLog",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "0003-add-compdef-to-zsh-completion.patch",
]
SPDX-FileCopyrightText = "google-cloud-cli contributors"
SPDX-License-Identifier = "Apache-2.0"
