--- Makefile
+++ Makefile
@@ -29,4 +29,10 @@ ntfs3-$(CONFIG_NTFS3_LZX_XPRESS) += $(addprefix lib/,\
 		lzx_common.o \
 		lzx_decompress.o \
 		xpress_decompress.o \
-		)
\ No newline at end of file
+		)
+
+all:
+	make -C /lib/modules/$(KVERSION)/build M=$(PWD) modules
+
+clean:
+	make -C /lib/modules/$(KVERSION)/build M=$(PWD) clean
\ No newline at end of file
