post_install() {
  systemd-sysusers teamcity.conf
  chown -R teamcity /opt/teamcity /var/lib/teamcity
  echo "If you want to use a different Java, set it in /etc/conf.d/teamcity"
  echo
  echo "To start Teamcity instance:"
  echo "  systemctl start teamcity-server"
  echo "  systemctl start teamcity-agent"
  echo
  echo "Default TeamCity port is 8111."
}

post_upgrade() {
  systemd-sysusers teamcity.conf
  chown -R teamcity /opt/teamcity /var/lib/teamcity
}
