post_install() {
  local install_dir='/usr/share/refind/themes/dracula'

  cd "$install_dir" || exit 1

  echo "Setup refind-theme-dracula-$1"
  echo "Executing ${install_dir}/setup.sh..."
  
  if ! bash setup.sh; then
    echo "###########################################################"
    echo "A problem occurred when running 'setup.sh', run it manually" 
    echo "###########################################################"    
  fi
}

post_upgrade() {
  post_install
}
