#!/bin/bash
# pathPre=`pwd`
# electronicWechatPath=/opt/electronic-wechat-uos-bin
# cd ${electronicWechatPath}
# ./electronic-wechat
# cd ${pathPre}
exec electron20 /opt/electronic-wechat-uos-bin/resources/app.asar
