#!/bin/sh

# As for now, PacketTracer works with built-in arch libraries
# If you exprerience any troubles, try to uncomment
# the following line        

export LD_LIBRARY_PATH="/usr/share/packettracer/bin" 

/usr/share/packettracer/bin/linguist "$@"

