<!DOCTYPE html>
<html lang='en'>
<head>
<title>nvidia-utils.install\trunk - svntogit/packages.git - Git clone of the 'packages' repository
</title>
<meta name='generator' content='cgit v1.2.1-1-g437b'/>
<meta name='robots' content='index, nofollow'/>
<link rel='stylesheet' type='text/css' href='/cgit.css'/>
<link rel='shortcut icon' href='/favicon.ico'/>
<link rel='alternate' title='Atom feed' href='https://git.archlinux.org/svntogit/packages.git/atom/trunk/nvidia-utils.install?h=packages/nvidia-utils' type='application/atom+xml'/>
<link rel='vcs-git' href='https://git.archlinux.org/svntogit/packages.git' title='svntogit/packages.git Git repository'/>
<link rel='vcs-git' href='git://git.archlinux.org/svntogit/packages.git' title='svntogit/packages.git Git repository'/>
<link rel='vcs-git' href='ssh://git.archlinux.org/srv/git/svntogit/packages.git' title='svntogit/packages.git Git repository'/>
</head>
<body>
	<div id="archnavbar"><!-- Arch Linux global navigation bar -->
		<div id="archnavbarlogo">
			<p><a href="http://www.archlinux.org/" title="Arch news, packages, projects and more"></a></p>
		</div>
		<div id="archnavbarmenu">
			<ul id="archnavbarlist">
				<li id="anb-home"><a href="http://www.archlinux.org/" title="Arch news, packages, projects and more">Home</a></li>
				<li id="anb-packages"><a href="http://www.archlinux.org/packages/" title="Arch Package Database">Packages</a></li>
				<li id="anb-forums"><a href="https://bbs.archlinux.org/" title="Community forums">Forums</a></li>
				<li id="anb-wiki"><a href="https://wiki.archlinux.org/" title="Community documentation">Wiki</a></li>
				<li id="anb-bugs"><a href="https://bugs.archlinux.org/" title="Report and follow bugs">Bugs</a></li>
				<li id="anb-sec"><a href="https://security.archlinux.org/" title="Security Tracker">Security</a></li>
				<li id="anb-aur"><a href="https://aur.archlinux.org/" title="Arch Linux User Repository">AUR</a></li>
				<li id="anb-download"><a href="http://www.archlinux.org/download/" title="Get Arch Linux">Download</a></li>
			</ul>
		</div>
	</div><!-- #archnavbar -->
<div id='cgit'><table id='header'>
<tr>
<td class='main'><a href='/'>index</a> : <a title='svntogit/packages.git' href='/svntogit/packages.git/'>svntogit/packages.git</a></td></tr>
<tr><td class='sub'>Git clone of the 'packages' repository
</td><td class='sub right'></td></tr></table>
<table class='tabs'><tr><td>
<a href='/svntogit/packages.git/?h=packages/nvidia-utils'>summary</a><a href='/svntogit/packages.git/refs/?h=packages/nvidia-utils'>refs</a><a href='/svntogit/packages.git/log/trunk/nvidia-utils.install?h=packages/nvidia-utils'>log</a><a class='active' href='/svntogit/packages.git/tree/trunk/nvidia-utils.install?h=packages/nvidia-utils'>tree</a><a href='/svntogit/packages.git/commit/trunk/nvidia-utils.install?h=packages/nvidia-utils'>commit</a><a href='/svntogit/packages.git/diff/trunk/nvidia-utils.install?h=packages/nvidia-utils'>diff</a><a href='/svntogit/packages.git/stats/trunk/nvidia-utils.install?h=packages/nvidia-utils'>stats</a></td><td class='form'><form class='right' method='get' action='/svntogit/packages.git/log/trunk/nvidia-utils.install'>
<input type='hidden' name='h' value='packages/nvidia-utils'/><select name='qt'>
<option value='grep'>log msg</option>
<option value='author'>author</option>
<option value='committer'>committer</option>
<option value='range'>range</option>
</select>
<input class='txt' type='search' size='10' name='q' value=''/>
<input type='submit' value='search'/>
</form>
</td></tr></table>
<div class='path'>path: <a href='/svntogit/packages.git/tree/?h=packages/nvidia-utils'>root</a>/<a href='/svntogit/packages.git/tree/trunk?h=packages/nvidia-utils'>trunk</a>/<a href='/svntogit/packages.git/tree/trunk/nvidia-utils.install?h=packages/nvidia-utils'>nvidia-utils.install</a></div><div class='content'>blob: 47847c7381cea41496ad252120ec0ab770530f50 (<a href='/svntogit/packages.git/plain/trunk/nvidia-utils.install?h=packages/nvidia-utils'>plain</a>)
<table summary='blob content' class='blob'>
<tr><td class='linenumbers'><pre><a id='n1' href='#n1'>1</a>
<a id='n2' href='#n2'>2</a>
<a id='n3' href='#n3'>3</a>
<a id='n4' href='#n4'>4</a>
<a id='n5' href='#n5'>5</a>
<a id='n6' href='#n6'>6</a>
<a id='n7' href='#n7'>7</a>
</pre></td>
<td class='lines'><pre><code>post_upgrade<span class="hl opt">() {</span>
  <span class="hl kwb">echo</span> <span class="hl str">&quot;If you run into trouble with CUDA not being available, run nvidia-modprobe first.&quot;</span>
<span class="hl opt">}</span>

post_install<span class="hl opt">() {</span>
  post_upgrade
<span class="hl opt">}</span>
</code></pre></td></tr></table>
</div> <!-- class=content -->
<div class="foot" style="padding-left:1em;padding-right:1em;">
<p>Copyright &copy; 2002-2018 <a href="mailto:jvinet@zeroflux.org"
title="contact Judd Vinet">Judd Vinet</a> and <a href="mailto:aaron@archlinux.org"
title="contact Aaron Griffin">Aaron Griffin</a>. The Arch Linux name and logo
are recognized trademarks. Some rights reserved. The registered trademark
Linux&reg; is used pursuant to a sublicense from LMI, the exclusive licensee
of Linus Torvalds, owner of the mark on a world-wide basis.</p>
</div>
</div> <!-- id=cgit -->
</body>
</html>
