infodir=usr/share/info
filelist=(gnat-style.info gnat_rm.info gnat_ugn.info)

post_install() {
  [ -x usr/bin/install-info ] || return 0
  for file in ${filelist[@]}; do
    install-info $infodir/$file.gz $infodir/dir 2> /dev/null
  done
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  [ -x usr/bin/install-info ] || return 0
  for file in ${filelist[@]}; do
    install-info --delete $infodir/$file.gz $infodir/dir 2> /dev/null
  done
}
