post_install() {
	xdg-icon-resource forceupdate --theme hicolor &> /dev/null
	update-desktop-database -q
	echo "==> Install your songs in ~/.stepmania-5.0/Songs ; you can find"
	echo "==> content at https://www.reddit.com/r/Stepmania/comments/2r1l2f/looking_for_more_song_packs_your_moderator/"
}

post_remove() {
	xdg-icon-resource forceupdate --theme hicolor &> /dev/null
	update-desktop-database -q
}
