post_install() {
cat <<"EOF"
Version 1.8.0 of nvidia-container-toolkit adds native cgroupv2 support and so
you no longer need to supply `--device /dev/nvida-...` arguments to docker and
(if applicable) you can remove the following kernel cli flag:

`systemd.unified_cgroup_hierarchy=false`

You might also need to re-enable c-groups in
/etc/nvidia-container-runtime/config.toml by ensuring `no-cgroups` is not set
to true.
EOF
}

post_upgrade() {
    post_install
}
