#!/bin/sh

if [[ "$1" != "-p" ]]; then
    WORKDIR=${XDG_CONFIG_HOME:-$HOME/.config}/hmcl
    mkdir -p $WORKDIR
    cd $WORKDIR
fi

exec /usr/lib/jvm/java-8-openjdk/jre/bin/java -jar "/usr/share/java/hmcl/hmcl.jar" "$@"
