post_install() {
    post_upgrade
    printf "==> To use gitea with openssh:\n"
    printf "    You may want to\n"
    printf "    usermod -d /var/lib/gitea/repos git\n"
    printf "==> To use gitea as SSH server on 22:\n"
    printf "    You may want to\n"
    printf "    setcap CAP_NET_BIND_SERVICE=+eip /usr/bin/gitea\n"
}

post_upgrade() {
    # set permissions indepent of host the package was build on
    chown -R git:git /var/lib/gitea /var/log/gitea
    chown -R root:git /etc/gitea
}
