[[library]]
name = "libqt6labsanimation"
file = "libQt6LabsAnimation"

[[library]]
name = "libqt6labsfolderlistmodel"
file = "libQt6LabsFolderListModel"

[[library]]
name = "libqt6labsqmlmodels"
file = "libQt6LabsQmlModels"

[[library]]
name = "libqt6labssettings"
file = "libQt6LabsSettings"

[[library]]
name = "libqt6labssharedimage"
file = "libQt6LabsSharedImage"

[[library]]
name = "libqt6labswavefrontmesh"
file = "libQt6LabsWavefrontMesh"

[[library]]
name = "libqt6qml"
file = "libQt6Qml"

[[library]]
name = "libqt6qmlcompiler"
file = "libQt6QmlCompiler"

[[library]]
name = "libqt6qmlcore"
file = "libQt6QmlCore"

[[library]]
name = "libqt6qmllocalstorage"
file = "libQt6QmlLocalStorage"

[[library]]
name = "libqt6qmlmodels"
file = "libQt6QmlModels"

[[library]]
name = "libqt6qmlnetwork"
file = "libQt6QmlNetwork"

[[library]]
name = "libqt6qmlworkerscript"
file = "libQt6QmlWorkerScript"

[[library]]
name = "libqt6qmlxmllistmodel"
file = "libQt6QmlXmlListModel"

[[library]]
name = "libqt6quick"
file = "libQt6Quick"

[[library]]
name = "libqt6quickcontrols2"
file = "libQt6QuickControls2"

[[library]]
name = "libqt6quickcontrols2basic"
file = "libQt6QuickControls2Basic"

[[library]]
name = "libqt6quickcontrols2basicstyleimpl"
file = "libQt6QuickControls2BasicStyleImpl"

[[library]]
name = "libqt6quickcontrols2fusion"
file = "libQt6QuickControls2Fusion"

[[library]]
name = "libqt6quickcontrols2fusionstyleimpl"
file = "libQt6QuickControls2FusionStyleImpl"

[[library]]
name = "libqt6quickcontrols2imagine"
file = "libQt6QuickControls2Imagine"

[[library]]
name = "libqt6quickcontrols2imaginestyleimpl"
file = "libQt6QuickControls2ImagineStyleImpl"

[[library]]
name = "libqt6quickcontrols2impl"
file = "libQt6QuickControls2Impl"

[[library]]
name = "libqt6quickcontrols2material"
file = "libQt6QuickControls2Material"

[[library]]
name = "libqt6quickcontrols2materialstyleimpl"
file = "libQt6QuickControls2MaterialStyleImpl"

[[library]]
name = "libqt6quickcontrols2universal"
file = "libQt6QuickControls2Universal"

[[library]]
name = "libqt6quickcontrols2universalstyleimpl"
file = "libQt6QuickControls2UniversalStyleImpl"

[[library]]
name = "libqt6quickdialogs2"
file = "libQt6QuickDialogs2"

[[library]]
name = "libqt6quickdialogs2quickimpl"
file = "libQt6QuickDialogs2QuickImpl"

[[library]]
name = "libqt6quickdialogs2utils"
file = "libQt6QuickDialogs2Utils"

[[library]]
name = "libqt6quickeffects"
file = "libQt6QuickEffects"

[[library]]
name = "libqt6quicklayouts"
file = "libQt6QuickLayouts"

[[library]]
name = "libqt6quickparticles"
file = "libQt6QuickParticles"

[[library]]
name = "libqt6quickshapes"
file = "libQt6QuickShapes"

[[library]]
name = "libqt6quicktemplates2"
file = "libQt6QuickTemplates2"

[[library]]
name = "libqt6quicktest"
file = "libQt6QuickTest"

[[library]]
name = "libqt6quickwidgets"
file = "libQt6QuickWidgets"
