[[library]]
name = "libgio"
file = "libgio-2.0"

[[library]]
name = "libglib"
file = "libglib-2.0"

[[library]]
name = "libgmodule"
file = "libgmodule-2.0"

[[library]]
name = "libgobject"
file = "libgobject-2.0"

[[library]]
name = "libgthread"
file = "libgthread-2.0"

[[library]]
name = "libgirepository"
file = "libgirepository-2.0"
