/*** Autogenerated by WIDL 5.0 from ../../wine-valve-git/include/wine/wined3d-interop.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __wined3d_interop_h__
#define __wined3d_interop_h__

/* Forward declarations */

#ifndef __IWineD3D11Texture2D_FWD_DEFINED__
#define __IWineD3D11Texture2D_FWD_DEFINED__
typedef interface IWineD3D11Texture2D IWineD3D11Texture2D;
#ifdef __cplusplus
interface IWineD3D11Texture2D;
#endif /* __cplusplus */
#endif

#ifndef __IWineD3D11Device_FWD_DEFINED__
#define __IWineD3D11Device_FWD_DEFINED__
typedef interface IWineD3D11Device IWineD3D11Device;
#ifdef __cplusplus
interface IWineD3D11Device;
#endif /* __cplusplus */
#endif

/* Headers for imported files */

#include <d3d11.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef void (__cdecl *gl_texture_callback)(unsigned int gl_texture,unsigned int gl_depth_texture,const void *data,unsigned int data_size);
/*****************************************************************************
 * IWineD3D11Texture2D interface
 */
#ifndef __IWineD3D11Texture2D_INTERFACE_DEFINED__
#define __IWineD3D11Texture2D_INTERFACE_DEFINED__

DEFINE_GUID(IID_IWineD3D11Texture2D, 0x267dc993, 0xd15e, 0x4015, 0xaa,0xac, 0xb7,0x55,0x9e,0x22,0x6c,0xc3);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("267dc993-d15e-4015-aaac-b7559e226cc3")
IWineD3D11Texture2D : public ID3D11Texture2D
{
    virtual void STDMETHODCALLTYPE access_gl_texture(
        gl_texture_callback callback,
        IWineD3D11Texture2D *depth_texture,
        const void *data,
        unsigned int data_size) = 0;

    virtual unsigned int STDMETHODCALLTYPE get_gl_texture(
        ) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IWineD3D11Texture2D, 0x267dc993, 0xd15e, 0x4015, 0xaa,0xac, 0xb7,0x55,0x9e,0x22,0x6c,0xc3)
#endif
#else
typedef struct IWineD3D11Texture2DVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IWineD3D11Texture2D *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IWineD3D11Texture2D *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IWineD3D11Texture2D *This);

    /*** ID3D11DeviceChild methods ***/
    void (STDMETHODCALLTYPE *GetDevice)(
        IWineD3D11Texture2D *This,
        ID3D11Device **ppDevice);

    HRESULT (STDMETHODCALLTYPE *GetPrivateData)(
        IWineD3D11Texture2D *This,
        REFGUID guid,
        UINT *pDataSize,
        void *pData);

    HRESULT (STDMETHODCALLTYPE *SetPrivateData)(
        IWineD3D11Texture2D *This,
        REFGUID guid,
        UINT DataSize,
        const void *pData);

    HRESULT (STDMETHODCALLTYPE *SetPrivateDataInterface)(
        IWineD3D11Texture2D *This,
        REFGUID guid,
        const IUnknown *pData);

    /*** ID3D11Resource methods ***/
    void (STDMETHODCALLTYPE *GetType)(
        IWineD3D11Texture2D *This,
        D3D11_RESOURCE_DIMENSION *pResourceDimension);

    void (STDMETHODCALLTYPE *SetEvictionPriority)(
        IWineD3D11Texture2D *This,
        UINT EvictionPriority);

    UINT (STDMETHODCALLTYPE *GetEvictionPriority)(
        IWineD3D11Texture2D *This);

    /*** ID3D11Texture2D methods ***/
    void (STDMETHODCALLTYPE *GetDesc)(
        IWineD3D11Texture2D *This,
        D3D11_TEXTURE2D_DESC *pDesc);

    /*** IWineD3D11Texture2D methods ***/
    void (STDMETHODCALLTYPE *access_gl_texture)(
        IWineD3D11Texture2D *This,
        gl_texture_callback callback,
        IWineD3D11Texture2D *depth_texture,
        const void *data,
        unsigned int data_size);

    unsigned int (STDMETHODCALLTYPE *get_gl_texture)(
        IWineD3D11Texture2D *This);

    END_INTERFACE
} IWineD3D11Texture2DVtbl;

interface IWineD3D11Texture2D {
    CONST_VTBL IWineD3D11Texture2DVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IWineD3D11Texture2D_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IWineD3D11Texture2D_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IWineD3D11Texture2D_Release(This) (This)->lpVtbl->Release(This)
/*** ID3D11DeviceChild methods ***/
#define IWineD3D11Texture2D_GetDevice(This,ppDevice) (This)->lpVtbl->GetDevice(This,ppDevice)
#define IWineD3D11Texture2D_GetPrivateData(This,guid,pDataSize,pData) (This)->lpVtbl->GetPrivateData(This,guid,pDataSize,pData)
#define IWineD3D11Texture2D_SetPrivateData(This,guid,DataSize,pData) (This)->lpVtbl->SetPrivateData(This,guid,DataSize,pData)
#define IWineD3D11Texture2D_SetPrivateDataInterface(This,guid,pData) (This)->lpVtbl->SetPrivateDataInterface(This,guid,pData)
/*** ID3D11Resource methods ***/
#define IWineD3D11Texture2D_GetType(This,pResourceDimension) (This)->lpVtbl->GetType(This,pResourceDimension)
#define IWineD3D11Texture2D_SetEvictionPriority(This,EvictionPriority) (This)->lpVtbl->SetEvictionPriority(This,EvictionPriority)
#define IWineD3D11Texture2D_GetEvictionPriority(This) (This)->lpVtbl->GetEvictionPriority(This)
/*** ID3D11Texture2D methods ***/
#define IWineD3D11Texture2D_GetDesc(This,pDesc) (This)->lpVtbl->GetDesc(This,pDesc)
/*** IWineD3D11Texture2D methods ***/
#define IWineD3D11Texture2D_access_gl_texture(This,callback,depth_texture,data,data_size) (This)->lpVtbl->access_gl_texture(This,callback,depth_texture,data,data_size)
#define IWineD3D11Texture2D_get_gl_texture(This) (This)->lpVtbl->get_gl_texture(This)
#else
/*** IUnknown methods ***/
static FORCEINLINE HRESULT IWineD3D11Texture2D_QueryInterface(IWineD3D11Texture2D* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static FORCEINLINE ULONG IWineD3D11Texture2D_AddRef(IWineD3D11Texture2D* This) {
    return This->lpVtbl->AddRef(This);
}
static FORCEINLINE ULONG IWineD3D11Texture2D_Release(IWineD3D11Texture2D* This) {
    return This->lpVtbl->Release(This);
}
/*** ID3D11DeviceChild methods ***/
static FORCEINLINE void IWineD3D11Texture2D_GetDevice(IWineD3D11Texture2D* This,ID3D11Device **ppDevice) {
    This->lpVtbl->GetDevice(This,ppDevice);
}
static FORCEINLINE HRESULT IWineD3D11Texture2D_GetPrivateData(IWineD3D11Texture2D* This,REFGUID guid,UINT *pDataSize,void *pData) {
    return This->lpVtbl->GetPrivateData(This,guid,pDataSize,pData);
}
static FORCEINLINE HRESULT IWineD3D11Texture2D_SetPrivateData(IWineD3D11Texture2D* This,REFGUID guid,UINT DataSize,const void *pData) {
    return This->lpVtbl->SetPrivateData(This,guid,DataSize,pData);
}
static FORCEINLINE HRESULT IWineD3D11Texture2D_SetPrivateDataInterface(IWineD3D11Texture2D* This,REFGUID guid,const IUnknown *pData) {
    return This->lpVtbl->SetPrivateDataInterface(This,guid,pData);
}
/*** ID3D11Resource methods ***/
static FORCEINLINE void IWineD3D11Texture2D_GetType(IWineD3D11Texture2D* This,D3D11_RESOURCE_DIMENSION *pResourceDimension) {
    This->lpVtbl->GetType(This,pResourceDimension);
}
static FORCEINLINE void IWineD3D11Texture2D_SetEvictionPriority(IWineD3D11Texture2D* This,UINT EvictionPriority) {
    This->lpVtbl->SetEvictionPriority(This,EvictionPriority);
}
static FORCEINLINE UINT IWineD3D11Texture2D_GetEvictionPriority(IWineD3D11Texture2D* This) {
    return This->lpVtbl->GetEvictionPriority(This);
}
/*** ID3D11Texture2D methods ***/
static FORCEINLINE void IWineD3D11Texture2D_GetDesc(IWineD3D11Texture2D* This,D3D11_TEXTURE2D_DESC *pDesc) {
    This->lpVtbl->GetDesc(This,pDesc);
}
/*** IWineD3D11Texture2D methods ***/
static FORCEINLINE void IWineD3D11Texture2D_access_gl_texture(IWineD3D11Texture2D* This,gl_texture_callback callback,IWineD3D11Texture2D *depth_texture,const void *data,unsigned int data_size) {
    This->lpVtbl->access_gl_texture(This,callback,depth_texture,data,data_size);
}
static FORCEINLINE unsigned int IWineD3D11Texture2D_get_gl_texture(IWineD3D11Texture2D* This) {
    return This->lpVtbl->get_gl_texture(This);
}
#endif
#endif

#endif


#endif  /* __IWineD3D11Texture2D_INTERFACE_DEFINED__ */

typedef void (__cdecl *user_cs_callback)(const void *data,unsigned int data_size);
/*****************************************************************************
 * IWineD3D11Device interface
 */
#ifndef __IWineD3D11Device_INTERFACE_DEFINED__
#define __IWineD3D11Device_INTERFACE_DEFINED__

DEFINE_GUID(IID_IWineD3D11Device, 0x8f02de7e, 0xd55d, 0x457b, 0x94,0x23, 0x83,0x45,0x6e,0x49,0xc5,0x8a);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("8f02de7e-d55d-457b-9423-83456e49c58a")
IWineD3D11Device : public IUnknown
{
    virtual void STDMETHODCALLTYPE run_on_command_stream(
        user_cs_callback callback,
        const void *data,
        unsigned int data_size) = 0;

    virtual void STDMETHODCALLTYPE wait_idle(
        ) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IWineD3D11Device, 0x8f02de7e, 0xd55d, 0x457b, 0x94,0x23, 0x83,0x45,0x6e,0x49,0xc5,0x8a)
#endif
#else
typedef struct IWineD3D11DeviceVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IWineD3D11Device *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IWineD3D11Device *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IWineD3D11Device *This);

    /*** IWineD3D11Device methods ***/
    void (STDMETHODCALLTYPE *run_on_command_stream)(
        IWineD3D11Device *This,
        user_cs_callback callback,
        const void *data,
        unsigned int data_size);

    void (STDMETHODCALLTYPE *wait_idle)(
        IWineD3D11Device *This);

    END_INTERFACE
} IWineD3D11DeviceVtbl;

interface IWineD3D11Device {
    CONST_VTBL IWineD3D11DeviceVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IWineD3D11Device_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IWineD3D11Device_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IWineD3D11Device_Release(This) (This)->lpVtbl->Release(This)
/*** IWineD3D11Device methods ***/
#define IWineD3D11Device_run_on_command_stream(This,callback,data,data_size) (This)->lpVtbl->run_on_command_stream(This,callback,data,data_size)
#define IWineD3D11Device_wait_idle(This) (This)->lpVtbl->wait_idle(This)
#else
/*** IUnknown methods ***/
static FORCEINLINE HRESULT IWineD3D11Device_QueryInterface(IWineD3D11Device* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static FORCEINLINE ULONG IWineD3D11Device_AddRef(IWineD3D11Device* This) {
    return This->lpVtbl->AddRef(This);
}
static FORCEINLINE ULONG IWineD3D11Device_Release(IWineD3D11Device* This) {
    return This->lpVtbl->Release(This);
}
/*** IWineD3D11Device methods ***/
static FORCEINLINE void IWineD3D11Device_run_on_command_stream(IWineD3D11Device* This,user_cs_callback callback,const void *data,unsigned int data_size) {
    This->lpVtbl->run_on_command_stream(This,callback,data,data_size);
}
static FORCEINLINE void IWineD3D11Device_wait_idle(IWineD3D11Device* This) {
    This->lpVtbl->wait_idle(This);
}
#endif
#endif

#endif


#endif  /* __IWineD3D11Device_INTERFACE_DEFINED__ */

/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __wined3d_interop_h__ */
