# 995d510d3099f2be343b1d6445a85bdc  amdgpu-pro-core_19.20-812932_all.deb/postinst
# Converted for arch linux:
post_install() {
    prefix=/opt/amdgpu-pro
    conf=/etc/ld.so.conf.d/10-amdgpu-pro.conf

    echo "$prefix/lib/x86_64-linux-gnu" >$conf
    echo "$prefix/lib/i386-linux-gnu" >>$conf
}

# 41e43dfaf280600942eab53da384100d  amdgpu-pro-core_19.20-812932_all.deb/prerm
# Converted for arch linux:
pre_remove() {
    rm -f /etc/ld.so.conf.d/10-amdgpu-pro.conf && /sbin/ldconfig
}
