# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Artem Vorotnikov <artem@vorotnikov.me>

_gemname=rb-inotify
pkgname=ruby-$_gemname
pkgver=0.9.5
pkgrel=1
pkgdesc='A Ruby wrapper for Linux'\''s inotify, using FFI'
arch=(any)
url='http://github.com/nex3/rb-inotify'
license=()
depends=(ruby ruby-ffi)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha512sums=('1ecc0142ed44358a2f51403736533e9854b5fc13cb81b552eb866310b60535b14e2ac6bfb6ee53bc1ee65ac14e51fc5a981e52f843607dbb3d8390c1d6c13e60')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/MIT-LICENSE" "$pkgdir/usr/share/licenses/$pkgname/MIT-LICENSE"
}
