# Colored makepkg-like functions
msg_blue() {
    printf "%s==>%s %s%s\n" "${blue}" "${bold}" "$1" "${all_off}"
}

note() {
    printf "%s==>%s NOTE:%s %s%s\n" "${blue}" "${yellow}" "${bold}" "$1" "${all_off}"
}

all_off="$(tput sgr0)"
bold="${all_off}$(tput bold)"
blue="${bold}$(tput setaf 4)"
yellow="${bold}$(tput setaf 3)"

post_install() {
    note "Custom flags should be put directly in: ~/.config/codium-flags.conf"
}

post_upgrade() {
    post_install
}
