post_install() {
  echo "Maybe you want the context menu icons enabled. This can be done in dconf or using the CLI:"
  echo "gsettings set org.gnome.desktop.interface menus-have-icons true"
  echo "DISCLAIMER: Notice that this is a system-wide configuration and it will change appearence in other programs too."

}

post_upgrade() {
  # Only show information if upgrading from 4.0.6 or older
  if [ $(vercmp $2 4.0.6-1) -le 0 ]; then
    post_install
  fi
}
