post_remove() {
    MK_CONF=$(grep -v '#' /etc/mkinitcpio.conf | grep zfs >/dev/null; echo $?);
    if [[ ${MK_CONF} == '0' && $1 == 'remove' ]]; then
        echo '>>> The ZFS packages have been removed, but "zfs" remains in the "hooks"'
        echo '>>> list in mkinitcpio.conf! You will need to remove "zfs" from the '
        echo '>>> "hooks" list and then regenerate the initial ramdisk.'
    fi
}
