# Colored makepkg-like functions
msg_blue() {
    printf "${blue}==>${bold} $1${all_off}\n"
}

note() {
    printf "${blue}==>${yellow} NOTE$1:${bold} $2${all_off}\n"
}

all_off="$(tput sgr0)"
bold="${all_off}$(tput bold)"
blue="${bold}$(tput setaf 4)"
yellow="${bold}$(tput setaf 3)"

post_install() {
    note 1 "This installs side-by-side with extra/firefox"
    note 2 "The launcher is called: 'firefox-beta'"
}

post_upgrade() {
    post_install
}
