post_install() {
	# Update icon cache.
	gtk-update-icon-cache -q -t -f usr/share/icons/hicolor

	# Note admin after install/update on how to change th update_check setting.
	cat << _EOF

	==> sublime-text-dev install/upgrade note:
	------------------------------------------------------------------------------
	To disable in-application reminders about new Sublime Text dev versions,
	add the following setting to your User Preferences file:
	"update_check": false

	The following is Simplified Chinese translation.

	==> Sublime Text 开发版本安装/升级注意事项:
	------------------------------------------------------------------------------
	要禁止 Sublime Text 开发版本的应用内升级提醒，请在您的用户配置
	文件中添加以下内容:
	"update_check": false

_EOF
}

post_upgrade() {
	post_install $1
}

post_remove() {
	# Update icon cache.
	gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}
