#!/bin/bash
#
# Usage: iptables-flush [6]
#

iptables=ip$1tables
if ! type -p "$iptables" &>/dev/null; then
  echo "error: invalid argument"
  exit 1
fi

while read -r table; do
  tables+=("/usr/share/iptables/empty-$table.rules")
done < <(nft list tables | sed -n "s/table ip$1 //p")

if (( ${#tables[*]} )); then
  cat "${tables[@]}" | "$iptables-restore"
fi
