#!/bin/sh

# Please note that Sublime Text 2 for some reason opens an empty instance
# if the project you're trying to open is already open in another instance,
# instead of just giving it focus.

BIN=/opt/sublime-text/sublime_text

PID=$(pidof -o %PPID ${BIN})
ARGS="--class=sublime-text"

if [[ ${1:(-16)} == ".sublime-project" ]]; then
	ARGS="${ARGS} --project"
fi

if [[ -n ${PID} ]]; then
	${BIN} ${ARGS} "$@"
else
	${BIN} ${ARGS} "$@" &
fi
