post_install() {
    gtk-update-icon-cache -qtf usr/share/icons/hicolor
    cat <<__EOF__
>>
>> If you have an NVIDIA card that supports libvdpau or Broadcom Crystal HD chips,
>> uncomment EnableLinuxHWVideoDecode=1 from /etc/adobe/mms.cfg.
>> If you run into problems, please contact nVidia or Broadcom along with your system config info / driver version.
>>
__EOF__
}

post_upgrade() {
    if  [ "$(vercmp $2 10.2.152.27-2)" -lt 0 ]; then
        post_install $1
    fi
}
