# arg 1:  the new package version
post_install() {
  update-desktop-database -q
  update-mime-database usr/share/mime >/dev/null
}

# arg 1:  the new package version
# arg 2:  the old package version
post_upgrade() {
 post_install $1
}

# arg 1:  the old package version
pre_remove() {
/bin/true
}

post_remove() {
  update-desktop-database -q
  update-mime-database usr/share/mime >/dev/null
}

op=$1
shift

$op "$@" 
