post_install() {
  echo "======================================================================="
  echo
  echo "This package does not contain the firmware of Xbox Wireless dongle."
  echo "To install the firmware: run \`cd /tmp && sudo /lib/xone/firmware.sh\`"
  echo "Or install from aur/xone-dongle-firmware"
  echo
  echo "======================================================================="
}
