post_install() {
    cat <<EOF

WARNING: Ensure you understand what you are doing

Please read in advance:
  AppArmor - Arch Wiki
  https://wiki.archlinux.org/title/AppArmor

Follow the project:
  AppArmor / apparmor · GitLab
  https://gitlab.com/apparmor/apparmor

For package build issues, visit:
  Issues · archlinuxcn/repo
  https://github.com/archlinuxcn/repo/issues

EOF
}

post_upgrade() {
    post_install
}
