post_upgrade() {
    echo ">>> You may need to delete discord's config directory ~/.config/discord"
    echo ">>> If you are using betterdiscord you may also need to reinstall that"
    echo ">>> Try this if discord is stuck on the updating screen or if nothing displays but a gray box"
    echo ">>> If you believe there is a problem with this AUR package please report it to the AUR page"
    echo ">>> If you believe there is a problem with Discord please report it to:"
    echo ">>> https://discord.gg/discord-testers or https://discord.gg/discord-linux."
    /opt/discord/postinst.sh > /dev/null
}
