post_upgrade() {
    echo ">>> You may need to delete discord's cache directory ~/.cache/discord"
    echo ">>> try this if discord is stuck on the updating screen or if nothing displays but a gray box"
    echo ">>> if this doesn't work ask for help in #linux in the Discord Developers server https://discord.gg/UT7AMAP"
    echo ">>> You may also want to check out the linux server for help as well https://discord.gg/e7GX27C"
}
