post_install() {
    echo -n "Updating vim help tags..."
    /usr/bin/vim --noplugins -u NONE -U NONE \
        --cmd ":helptags /usr/share/vim/vimfiles/doc" --cmd ":q" > /dev/null 2>&1
    echo "done."
}

post_upgrade() {
  post_install $1
}

post_remove() {
    echo -n "Updating vim help tags..."
    /usr/bin/vim --noplugins -u NONE -U NONE \
        --cmd ":helptags /usr/share/vim/vimfiles/doc" --cmd ":q" > /dev/null 2>&1
    echo "done."
}

op=$1
shift

$op $*
