#!/bin/bash

usage() {
    cat <<EOF
Usage: xml2-config [OPTION]

Known values for OPTION are:

  --libs                print library linking information
                        add --dynamic to print only shared libraries
  --cflags              print pre-processor and compiler flags
  --modules             module support enabled
  --help                display this help and exit
  --version             output version information
EOF
    exit $1
}

if (( $# < 1 )); then
    usage 1
fi

pc_args=()
libs=0
libflag=--static

for arg; do
    case $arg in
        --help) usage 0 ;;
        --version) pc_args+=(--version) ;;
        --cflags) pc_args+=(--cflags) ;;
        --modules) pc_args+=(--variable=modules) ;;
        --libs) libs=1 ;;
        --dynamic) libflag=--shared ;;
        *) usage 1 ;;
    esac
done

if (( libs )); then
    pc_args+=(--libs $libflag)
fi

exec pkg-config "${pc_args[@]}" libxml-2.0
