post_install() {
  # Execute create_ap without asking for a password
  echo "ALL ALL=NOPASSWD: /usr/bin/create_ap" | (sudo su -c 'EDITOR="tee -a" visudo -f /etc/sudoers.d/create_ap')

  echo ""
  echo "Start the hotspot service on startup (using your saved configuration) with:"
  echo "systemctl enable create_ap"
  echo ""
}

post_remove() {
  sudo rm /etc/sudoers.d/create_ap

  echo ""
  echo "Optionally remove config file:"
  echo "sudo rm /etc/wh.config"
  echo ""
}
