diff --unified --recursive --text linux-wifi-hotspot-3.5.1.orig/src/scripts/Makefile linux-wifi-hotspot-3.5.1.new/src/scripts/Makefile
--- linux-wifi-hotspot-3.5.1.orig/src/scripts/Makefile	2020-11-13 17:02:11.000000000 -0700
+++ linux-wifi-hotspot-3.5.1.new/src/scripts/Makefile	2021-01-17 09:44:36.708721295 -0700
@@ -9,7 +9,7 @@
 install:
 	install -CDm755 create_ap $(DESTDIR)$(BINDIR)/create_ap
 	install -CDm644 create_ap.conf $(DESTDIR)/etc/create_ap.conf
-	[ ! -d $(DESTDIR)/lib/systemd/system ] || install -CDm644 create_ap.service $(DESTDIR)/lib/systemd/system/create_ap.service
+	install -CDm644 create_ap.service $(DESTDIR)$(PREFIX)/lib/systemd/system/create_ap.service
 	install -CDm644 bash_completion $(DESTDIR)$(PREFIX)/share/bash-completion/completions/create_ap
 	install -CDm644 README.md $(DESTDIR)$(PREFIX)/share/doc/create_ap/README.md
 	install -CDm755 wihotspot $(DESTDIR)$(BINDIR)/wihotspot
