pre_upgrade() {
  NEW=$1
  OLD=$2

  if [[ "$OLD" == "3.7"* || "$OLD" == "3.6"* ]]; then
    echo "Cleaning up previous flutter installation."
    rm -rf "/opt/flutter"
  fi
}

post_upgrade() {
  NEW=$1
  OLD=$2

  if [[ "$OLD" == "3.7"* || "$OLD" == "3.6"* ]]; then
    if grep -q "flutterusers" /etc/group; then
      echo "Removing group flutterusers as no longer needed."
      groupdel "flutterusers"
    fi
  fi
}
