post_install() {
cat << _EOF

Alternative usage:
    mkdir -p ~/MAA
    ln -s /usr/share/maa-assistant-arknights/Python/asst ~/MAA
    cp /usr/share/maa-assistant-arknights/Python/sample.py ~/MAA
  edit sample.py, e.g.:
    Asst.load(path='/usr/share/maa-assistant-arknights', 
              user_dir=user_dir=pathlib.Path.home() / '.cache/maa-assistant-arknights')
_EOF
}

post_upgrade() {
    post_install
}
