post_install() {
  echo "Please add 'dkms' to the HOOKs array in /etc/mkinitcpio.conf (position don't matter). Make sure to update 'linux-headers' (or whatever kernel headers you use) before the image creation to prevent build failure."
}

post_upgrade() {
  echo "SyncFirst is deprecated as of pacman v4.1. Make sure to manually update 'linux-headers' (or whatever kernel headers you use) before the image creation to prevent build failure."
}

