# Maintainer: Metal A-wing <1 at 233 dot email>
# Contributor: Carsten Feuls <archlinux@carstenfeuls.de>
# Generated by gem2arch (https://github.com/anatol/gem2arch)

_gemname=method_source
pkgname=ruby-$_gemname
pkgver=0.9.0
pkgrel=2
pkgdesc='retrieve the sourcecode for a method'
arch=(any)
url='http://banisterfiend.wordpress.com'
license=()
depends=(ruby ruby-rdoc)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('f0286dc6f0e77c3622a37c385c8638270063210c')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
