#!/bin/bash -e
XDG_DATA_HOME=${XDG_DATA_HOME:-~/.local/share}
RIME_DIR=${RIME_DIR:-$XDG_DATA_HOME/fcitx5/rime}
if [[ -d $RIME_DIR ]];then
  cp -r $RIME_DIR $RIME_DIR-sbxlm-init-backup-"$(date +%s)"
fi
mkdir -p $RIME_DIR
for f in /usr/share/sbxlm/init-userdb/*.tar.gz;do
  tar xf $f --directory="$RIME_DIR"
done
cp /usr/share/rime-data/default.custom.yaml $RIME_DIR
