#!/bin/sh

post_upgrade() {
  # We used to package /boot/grub/grub.cfg, but there is no reason to.
  # Remove the file from package, but move real file back in place.
  if [ ! -f /boot/grub/grub.cfg -a -f /boot/grub/grub.cfg.pacsave ]; then
    mv /boot/grub/grub.cfg.pacsave /boot/grub/grub.cfg
  fi
}

post_install() {
  cat << 'EOM'
Generate your bootloader configuration with:
  grub-mkconfig -o /boot/grub/grub.cfg
EOM
}

