# Colored makepkg-like functions
msg_blue() {
    printf "${BLUE}==>${ALL_OFF}${BOLD} ${1}${ALL_OFF}\n"
}

note() {
    printf "${BLUE}==>${ALL_OFF}${YELLOW} NOTE:${ALL_OFF}${BOLD} ${1}${ALL_OFF}\n"
}

ALL_OFF="$(tput sgr0)"
BOLD="$(tput bold)"
BLUE="${BOLD}$(tput setaf 4)"
YELLOW="${BOLD}$(tput setaf 3)"

_update() {
    msg_blue "Updating desktop MIME database..."
    update-desktop-database -q
    msg_blue "Updating icon cache.."
    gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor
}

post_install() {
    _update
    note "The binary is called: 'google-chrome-unstable'"
}


post_upgrade() {
    post_install
}


post_remove() {
    _update
}