# A colored makepkg-like function
msg_blue() {
    printf "${BLUE}==>${ALL_OFF}${BOLD} ${1}${ALL_OFF}\n"
}

ALL_OFF="$(tput sgr0)"
BOLD="$(tput bold)"
BLUE="${BOLD}$(tput setaf 4)"

post_install() {
    msg_blue "Updating desktop MIME database..."
    update-desktop-database -q
    msg_blue "Updating icon cache.."
    gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor
}

post_upgrade() {
    post_install
}

post_remove() {
    post_install
}