# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Artem Vorotnikov <artem@vorotnikov.me>

_gemname=slop
pkgname=ruby-$_gemname-3
pkgver=3.6.0
pkgrel=1
pkgdesc='Simple Lightweight Option Parsing'
arch=(any)
url='http://github.com/leejarvis/slop'
license=(MIT)
depends=(ruby ruby-rdoc)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha512sums=('876e5a9413c412648d7dc04472014858a566f923c58a076c7cbd03a347074b3912a97a7b7ed16b1fdefab00e6f322675b60e816dea574b7abbf635abe7c8946b')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
