# nginx.vh.default.conf -- openresty AUR package
# This file is installed to /etc/openresty/conf.d/default.conf and is loaded
# via the `include /etc/openresty/conf.d/*.conf;` directive in nginx.conf.

server {
    listen       80;
    server_name  localhost;

    location / {
        root   /opt/openresty/nginx/html;
        index  index.html index.htm;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /opt/openresty/nginx/html;
    }
}
