# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: a-wing <1@233.email>

_gemname=marcel
pkgname=ruby-$_gemname
pkgver=0.3.3
pkgrel=2
pkgdesc='Simple mime type detection using magic numbers, filenames, and extensions'
arch=(any)
url='https://github.com/basecamp/marcel'
license=(MIT)
depends=(ruby ruby-mimemagic)
makedepends=(ruby-rdoc)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('a4cf7bd4bd3cc8da6275133dbc9745458653fdf4')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/MIT-LICENSE" "$pkgdir/usr/share/licenses/$pkgname/MIT-LICENSE"
}
