post_install() {
    echo "Please make sure that you have Android SDK Platform-tools and Build-tools installed."
    echo
    echo "There are two ways to install:"
    echo "1.) Package android-sdk-platform-tools and android-sdk-build-tools from AUR"
    echo "or 2.) via Android SDK Manager"
    update-desktop-database -q
}

post_upgrade() {
    update-desktop-database -q
}

post_remove() {
    update-desktop-database -q
}
