[[library]]
name = "libclang"

[[library]]
name = "libclang_cpp"
file = "libclang-cpp"

[[binary]]
name = "clang"

[[binary]]
name = "clang_apply_replacements"
file = "clang-apply-replacements"

[[binary]]
name = "clang_check"
file = "clang-check"

[[binary]]
name = "clang_format"
file = "clang-format"

[[binary]]
name = "clang_scan_deps"
file = "clang-scan-deps"

[[binary]]
name = "clang_tidy"
file = "clang-tidy"
