#!/usr/bin/env bash

mkdir --parents /var/run/keyd-bwrap
bwrap --unshare-cgroup --unshare-ipc --unshare-net --unshare-pid --unshare-uts --die-with-parent \
      --ro-bind / / \
      --tmpfs /home --tmpfs /root --tmpfs /run --tmpfs /sys --tmpfs /tmp \
      --dev /dev --proc /proc \
      --dev-bind /dev/input /dev/input --dev-bind /dev/uinput /dev/uinput \
      --bind /var/run/keyd-bwrap /var/run \
      keyd "${@}"
