# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Harry <harry@h313.info>

_gemname=rack-test
pkgname=ruby-$_gemname
pkgver=1.1.0
pkgrel=1
pkgdesc='Simple testing API built on Rack'
arch=(any)
url='http://github.com/rack-test/rack-test'
license=(MIT)
depends=(ruby ruby-rack)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('b80bc5ca38a885e747271675ba91dd3d02136bf1')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/MIT-LICENSE.txt" "$pkgdir/usr/share/licenses/$pkgname/MIT-LICENSE.txt"
}
