post_install() {
  update-mime-database /usr/share/mime 1> /dev/null
  echo "update desktop mime database..."
  update-desktop-database -q
  gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  /bin/true
}

post_remove() {
  update-mime-database /usr/share/mime 1> /dev/null
  echo "update desktop mime database..."
  update-desktop-database -q
}
