post_upgrade() {
  rootpartlabel=$(lsblk -pilno partlabel,type,mountpoint | grep -G 'part +/$' |  head -n1 | cut -d " " -f1)
  sed -i 's/root=PARTLABEL=must-replace-me/root=PARTLABEL='"$rootpartlabel"'/g' /boot/extlinux/extlinux.conf
  rockchip-write-dtbos --uboot@root
}

post_install() {
  post_upgrade
}

post_remove() {
  rm -vf /boot/dtbs/*-tojoin.dtb
  rm -vf /boot/dtbs/*-joined.dtb
  rm -vf /boot/dtbos/*.dtbo
}

