#!/usr/bin/env bash
# ./check4u -- check for updates of a software package

ocaml-menhir_latest() {
    local WEBPAGE='http://opam.ocaml.org/packages/menhir/'
    local DOWNLOAD_LINK=`curl --silent $WEBPAGE |
         grep -oP --color=NEVER '\d+/archive\.tar\.gz<'`
    LATEST=${DOWNLOAD_LINK%/archive.tar.gz<}
}
ocaml-menhir_current() {
    source PKGBUILD &&
        CURRENT="$pkgver"
}

ocaml-menhir_latest && ocaml-menhir_current

if [[ "$LATEST" != "$CURRENT" ]]; then
    echo -e "Latest release   : $LATEST"
    echo -e "Currently on AUR : $CURRENT"
    exit 1
fi
