# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: Harry <arandomawesomegeek@gmail.com>

_gemname=rails-dom-testing
pkgname=ruby-$_gemname
pkgver=2.0.1
pkgrel=1
pkgdesc='Dom and Selector assertions for Rails applications'
arch=(any)
url='https://github.com/rails/rails-dom-testing'
license=(MIT)
depends=(ruby ruby-nokogiri ruby-activesupport)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('26cd420f73c38658c5ee4b7758acbe511d73bade')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
}
