# arg 1:  the new package version
# arg 2:  the old package version

name="mentohust"

tips(){
	echo ">>> If you want to autorun ${name},"
	echo ">>> run the following command as root,"
	echo ">>> systemctl enable ${name}.service"
}

post_install () {
	echo ">>> For first time, you must run '$name' to configure once."
	echo ">>> Or you may just manually edit /etc/${name}.conf"
	echo ""
	tips
}

post_upgrade() {
	tips
}

