post_install() {
  if ! getent passwd gdm >/dev/null; then
    groupadd -g 120 gdm
    useradd -c 'Gnome Display Manager' -u 120 -g gdm -d /var/lib/gdm -s /sbin/nologin gdm
    passwd -ql gdm > /dev/null
    chown -R gdm:gdm /var/lib/gdm > /dev/null
    chown root:gdm /var/log/gdm > /dev/null
  fi
}

post_remove() {
  getent passwd gdm >/dev/null 2>&1 && userdel gdm
  getent group gdm >/dev/null 2>&1 && groupdel gdm
}

