#!/usr/bin/bash

# This is your Application ID, avoid conflict
appID="com.onlyoffice.desktopeditors"

# This is a friendly name of an application. It should only contain ASCII characters and not spaces.
friendlyName="OnlyOffice"

# This is the state directory of your application, which is located under "XDG_DATA_HOME"
stateDirectory="OnlyOffice_Data"

# This is the target executable to launch
#launchTarget="gtk4-demo"

# Takes a boolean value or string "adaptive". When true, do not process XAuth files and forces wayland input method. "adaptive" enables this option on Wayland and vice versa. Generally this should be adaptive when possible.
waylandOnly="false"

# Takes boolean value.
bindInputDevices="false"

# Takes boolean value. Binds /dev/video* into the sandbox. Required if target application uses /dev/video* interfaces directly instead of v4l2.
bindCameras="false"

# Takes boolean value. Binds PipeWire socket into the sandbox. Required if target application doesn't use Portals.
bindPipewire="false"

# Expose all GPUs. Takes boolean value, usually used in games.
gameMode="false"

# Wake the application using D-Bus calls towards StatusNotifiers.
dbusWake="false"

# Below you can set envs that will be imported into the application sandbox

#bwBindPar="/home"
