# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: kulpae <my.shando@googlemail.com>

_gemname=json_pure
pkgname=ruby-$_gemname
pkgver=1.8.3
pkgrel=1
pkgdesc='JSON Implementation for Ruby'
arch=(any)
url='http://flori.github.com/json'
license=(Ruby)
depends=(ruby)
options=(!emptydirs)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('8deab664226574ff23a2f199d24ad18a42a9b10e')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
}
