version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".gitignore",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*sysusers.conf",
    "*.tmpfiles",
    "*tmpfiles.conf",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
    "lilac.yaml",
    "lilac.py",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "0001-Don-t-rely-on-transparent-decompression-in-list_aur.patch",
    "0002-Update-for-pacman-7.1.patch",
]
SPDX-FileCopyrightText = "paru contributors"
SPDX-License-Identifier = "GPL-3.0-or-later"
